version: '3.4'

services:
  wastebot:
    image: wastebot
    build:
      context: krakenfutures/wastebot
      dockerfile: krakenfutures/wastebot/Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8090:8090
      - 5005:5005
